name: surface
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.3.0
  - numpy=1.23.5
  - obspy=1.2.2
  - matplotlib=3.4.2
  - tqdm=4.61.1
  #- dateutil=2.8.1
  - pytz=2021.1
  - scipy=1.8.1
  - scikit-learn=0.24.2
  - joblib=1.0.1
  - seaborn=0.11.2
  #- zenodo_get=1.5.1
