# File: config.yml

# Path to the common dataset
common_dataset_path: '../Results/common_train_dataset_reduced.csv'

# Path to the standard scaler parameters
scaler_params_path: '../Results/params_standard_scaler_rf.csv'

# Parameters for bandpass filter function
bandpass_filter:
  lowcut: 1
  highcut: 10
  fs: 100
  num_corners: 4

# Number of CPUs to use
num_cpus: 48

# IRIS client settings
iris_client: IRIS

# Stations on which to run the detector
stations_id:
  - UW.RCM
  - UW.STAR
  - CC.OBSR

# Start time for the detector
starttime: "2020-04-09T13:23:30"

# Duration (in seconds) for which to run the detector
dur: 1800

# Sampling frequency
samp_freq: 100

# Input window length
win: 150

# Stride for the detector (time x freq)
stride: 3000

# Location code
location: "*"
